### ISSUE TITLE
The play/pause doesn't work

### ISSUE THREAD

**Issue by Mystik01** [divyanshu-in/soundsharp-musicplayer-tkinter#1]
The play and pause button doesn't work but everything else is great!
I think you or someone would have to ad like 4 buttons for pause, stop, play, unpause.

**Comment by Mystik01** [comment]
Ok check I've edited it, you can see my PR here if you want to update it: https://github.com/divyanshu-in/soundsharp-musicplayer-tkinter/pull/2

**Comment by divyanshu-in** [comment]
> The play and pause button doesn't work but everything else is great!

Thanks! for showing interest into this repo!!
actually it was my first project and I didn't put much effort into it, that's why it has too many flaws.
 btw nice work dude code looks good and more optimized than before.

**Comment by Mystik01** [comment]
yo bro no problem, I might another feature so you can add individual songs too not just a whole folder, 
also I've made a music slider for it which I'll push when I get home as I'm away at the moment.  
This was actually quite fun to build on , I don't usually use Python, so this is kind of a refresher for me as I normally use JavaScript and make Discord Bots lol.
